server:
  port: 5008
spring:
  profiles:
    active: dev
  application:
    name: bookinfo
  data:
      mongodb:
        uri: mongodb://172.93.42.240:27017/bookinfo
  redis:
    database: 0
    host: 172.93.42.240
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
sftp:
  url: 172.93.42.240
  port: 28592
  username: root
  password: xjw13579
file:
  path: /root/tale/resources/upload2
  url: https://www.swapassn.com/upload2/