server:
  port: 5008
spring:
  profiles:
    active: dev
  application:
    name: bookinfo
  data:
      mongodb:
        uri: mongodb://172.93.42.240:27017/bookinfo
  redis:
    database: 0
    host: 172.93.42.240
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0